=== exporl/apex/data/schemas/apexconfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xml:lang="en-US"
        targetNamespace="http://med.kuleuven.be/exporl/apex/4.1.0/experiment"
        xmlns:apex="http://med.kuleuven.be/exporl/apex/4.1.0/experiment">

        <xs:annotation>
            <xs:documentation xml:lang="en-US">
                Apex main config file schema
            </xs:documentation>
        </xs:annotation>

        <xs:complexType name="drivernameType" mixed="true">
            <xs:attribute name="driver" type="xs:Name"  use="required"/>
        </xs:complexType>

        <xs:complexType name="soundcardType">
            <xs:sequence>
                <xs:element name="drivername" type="apex:drivernameType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"  use="required"/>
        </xs:complexType>

        <xs:complexType name="cohDriverType" mixed="true">
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>

        <xs:element name="apex">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="paths">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="pluginScriptLibrary" type="xs:anyURI" minOccurs="0">
                                    <xs:annotation>
                                        <xs:documentation>
                                            Name of main script library. Will be searched for in the plugins path and will be concatenated to any
                                            XML generating plugin.
                                        </xs:documentation>
                                    </xs:annotation>
                                </xs:element>
                                <xs:element name="xslt" type="xs:anyURI" minOccurs="0" >
                                    <xs:annotation>
                                        <xs:documentation>URL where the xslt scripts reside to be used for transformation of results files. This URI will be used to set the xml-stylesheet processing instruction in the results file.</xs:documentation>
                                    </xs:annotation>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="soundcards">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="card" type="apex:soundcardType" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="cohdrivers" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="cohdriver" type="apex:cohDriverType" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="prefixes" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="prefix" minOccurs="0" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="xs:anyURI">
                                                <xs:attribute name="id" use="required" type="xs:ID"></xs:attribute>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="bertha" type="xs:boolean" minOccurs="0">
                        <xs:annotation>
                            <xs:documentation>
                                Use bertha for audio processing.
                                When not provided this defaults to true.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element name="studyshareurl" type="xs:anyURI" minOccurs="0">
                        <xs:annotation>
                          <xs:documentation>
                            Url which will be opened on sharing the public key from the study dialog.
                          </xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element name="interactive" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="constraints" minOccurs="0">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="constraint" minOccurs="0" maxOccurs="unbounded">
                                                <xs:complexType>
                                                    <xs:simpleContent>
                                                        <xs:extension base="xs:string">
                                                            <xs:attribute name="expression" type="xs:string"></xs:attribute>
                                                        </xs:extension>
                                                    </xs:simpleContent>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                    <xs:unique name="unique-expression">
                                        <xs:selector xpath="./constraint"/>
                                        <xs:field xpath="@expression"/>
                                    </xs:unique>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="useInstallationWideSettings" type="xs:boolean" minOccurs="0">
                        <xs:annotation>
                            <xs:documentation>
                                Specify whether to use user-specific settings or installation-wide settings. User-specific settings are
                                stored in a user specific location (on windows under [HKEY_CURRENT_USER\Software\ExpORL\APEX] in the
                                registry, on linux in $HOME/.config/ExpORL/APEX.conf). Installation-wide settings are stored in the folder
                                where the apex binary resides (e.g. /path/to/apex-installation/config/ExpORL/APEX.ini).
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>

                </xs:sequence>
                <xs:attribute name="version" use="required" type="xs:positiveInteger"></xs:attribute>
            </xs:complexType>
        </xs:element>
    </xs:schema>

=== exporl/apex/data/config/apexconfig.xml
<?xml version='1.0' encoding='UTF-8'?>
<apex:apex xmlns:apex="http://med.kuleuven.be/exporl/apex/4.1.0/experiment" version="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://med.kuleuven.be/exporl/apex/4.1.0/experiment https://exporl.med.kuleuven.be/apex/schemas/4.1.0/apexconfig.xsd">
  <paths>
    <pluginScriptLibrary>pluginscriptlibrary.js</pluginScriptLibrary>
  </paths>
  <soundcards>
    <card id="RME">
      <drivername driver="asio">ASIO Hammerfall DSP</drivername>
      <drivername driver="portaudio">HDSP Analog Out (1+2)(1)</drivername>
    </card>
    <card id="LynxONE">
      <drivername driver="asio">LynxONE</drivername>
      <drivername driver="portaudio">LynxONE FIXME</drivername>
    </card>
    <card id="Audiophile">
      <drivername driver="asio">M-Audio Audiophile</drivername>
      <drivername driver="portaudio">M-Audio Audiophile USB</drivername>
    </card>
    <card id="SoundMax">
      <drivername driver="asio">NULL</drivername>
      <drivername driver="portaudio">SoundMAX Digital Audio</drivername>
    </card>
    <card id="default">
      <drivername driver="asio">default</drivername>
      <drivername driver="portaudio">default</drivername>
      <drivername driver="jack">default</drivername>
      <drivername driver="qtaudio">default</drivername>
      <drivername driver="dummy">default</drivername>
    </card>
    <card id="macdefaultout">
      <drivername driver="asio">NULL</drivername>
      <drivername driver="portaudio">Built-in Output</drivername>
      <drivername driver="jack">NULL</drivername>
    </card>
  </soundcards>
  <cohdrivers>
    <cohdriver id="l34-cic3-0">protoslave: nic: l34-cic3-0</cohdriver>
    <cohdriver id="l34-cic3-1">protoslave: nic: l34-cic3-1</cohdriver>
    <cohdriver id="l34-cic3-2">protoslave: nic: l34-cic3-2</cohdriver>
    <cohdriver id="l34-cic4-0">protoslave: nic: l34-cic4-0</cohdriver>
    <cohdriver id="l34-cic4-1">protoslave: nic: l34-cic4-1</cohdriver>
    <cohdriver id="l34-cic4-2">protoslave: nic: l34-cic4-2</cohdriver>
    <cohdriver id="nic3-l34-codacs-0">protoslave: slave=nic3slave,verbose=true,args=extendedamplituderange allowimplantcommands; platform=L34,implant=CIC4,auto_pufs=off,go_live=off,min_pulse_width_us=12.0,flagged_electrodes=</cohdriver>
    <cohdriver id="nic3-l34-codacs-1">protoslave: slave=nic3slave,verbose=true,args=extendedamplituderange allowimplantcommands; platform=L34,implant=CIC4,auto_pufs=off,go_live=on,min_pulse_width_us=12.0,flagged_electrodes=</cohdriver>
    <cohdriver id="nic3-rfgenxs-cic4-mp12-0">protoslave: slave=nic3slave,verbose; platform=RFGenXS,implant=CIC4,auto_pufs=off,go_live=off,min_pulse_width_us=25.0,flagged_electrodes=,latency_ms=1000,mode=MP1+2</cohdriver>
    <cohdriver id="nic3-rfgenxs-cic4-mp12-1">protoslave: slave=nic3slave,verbose; platform=RFGenXS,implant=CIC4,auto_pufs=off,go_live=on,min_pulse_width_us=25.0,flagged_electrodes=,latency_ms=1000,mode=MP1+2,signal_path=left</cohdriver>
    <cohdriver id="nic3-rfgenxs-cic4-mp12-2">protoslave: slave=nic3slave,verbose; platform=RFGenXS,implant=CIC4,auto_pufs=off,go_live=on,min_pulse_width_us=25.0,flagged_electrodes=,latency_ms=1000,mode=MP1+2,signal_path=right</cohdriver>
    <cohdriver id="nic3-l34-cic4-mp12-0">protoslave: slave=nic3slave,verbose; platform=L34,implant=CIC4,auto_pufs=off,go_live=off,min_pulse_width_us=25.0,flagged_electrodes=,latency_ms=1000,mode=MP1+2</cohdriver>
    <cohdriver id="nic3-l34-cic4-mp12-1">protoslave: slave=nic3slave,verbose; platform=L34,implant=CIC4,auto_pufs=off,go_live=on,min_pulse_width_us=25.0,flagged_electrodes=,latency_ms=1000,mode=MP1+2</cohdriver>
    <cohdriver id="nic4-sp16-cic4-mp12-0">protoslave: nic4: implant=CIC4,latency_ms=200,mode=MP1+2,go_live=off</cohdriver>
    <cohdriver id="nic4-sp16-cic4-mp12-1">protoslave: nic4: implant=CIC4,latency_ms=200,mode=MP1+2,go_live=on</cohdriver>
    <cohdriver id="nic4-sp16-cic4-mp1-0">protoslave: nic4: implant=CIC4,latency_ms=200,mode=MP1,go_live=off</cohdriver>
    <cohdriver id="nic4-sp16-cic4-mp1-1">protoslave: nic4: implant=CIC4,latency_ms=200,mode=MP1,go_live=on</cohdriver>
    <cohdriver id="nic4-sp16-cic4-mp2-0">protoslave: nic4: implant=CIC4,latency_ms=200,mode=MP2,go_live=off</cohdriver>
    <cohdriver id="nic4-sp16-cic4-mp2-1">protoslave: nic4: implant=CIC4,latency_ms=200,mode=MP2,go_live=on</cohdriver>
    <cohdriver id="nic4-sp16-cic4-bp-0">protoslave: nic4: implant=CIC4,latency_ms=200,mode=BP,go_live=off</cohdriver>
    <cohdriver id="nic4-sp16-cic4-bp-1">protoslave: nic4: implant=CIC4,latency_ms=200,mode=BP,go_live=on</cohdriver>
  </cohdrivers>
  <prefixes>
    <prefix id="regression">../stimuli</prefix>
    <prefix id="speechmaterials">j:/GBW-0226_ExpORL/speechmaterials_0016</prefix>
    <prefix id="pictures">../../pictures</prefix>
  </prefixes>
  <bertha>true</bertha>
  <studyshareurl>
    https://exporl.med.kuleuven.be/apex-study
  </studyshareurl>
  <interactive>
    <constraints>
      <constraint expression="apex:apex/results[1]/subject[1]">
        ([a-zA-Z][0-3][0-9][a-zA-Z][0-9][0-9]){0,1}
      </constraint>
    </constraints>
  </interactive>
  <!-- Specify whether to use user-specific settings (default) or installation-wide settings.-->
  <useInstallationWideSettings>false</useInstallationWideSettings>
</apex:apex>
